### ISSUE TITLE
Admins can't add room preferences on behalf of faculty

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/cas#352]
**[Original report](https://bitbucket.org/laborstudents/cas-flask/issue/352) by Scott Heggen (Bitbucket: [sheggen](https://bitbucket.org/sheggen), GitHub: [sheggen](https://github.com/sheggen)).**

----------------------------------------

Some \(one\) faculty is having trouble using room preference. Cause currently unknown, but appears to be user error, not our system, for the moment. 

The admins can’t add a room preference for this faculty. There’s no interface for it. Currently, they’d have to assign the class to themselves, add the preferences, then remove themselves from the course. 

Do we want a UI for admins to see all room preferences? Bring it into the courses page as part of the edit modal?

**Comment by bryantal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CAS #352: Admins can't add room preferences on behalf of faculty #352](https://trello.com/c/gj4SDmQm/257-cas-352-admins-cant-add-room-preferences-on-behalf-of-faculty-352)

**Comment by Sandesh-L** [comment]
There is already a PR for this issue PR #413 branch: `admin-add-room-preferences-issues352` but it was sent back because too much of the code was duplicated, after resolving this issue.
`add-instructor-names-414` (another branch) and `admin-add-room-preferences-issues352`  need to be resolved together (there is a merge conflict) and created into one single PR.

**Comment by BrianRamsay** [comment]
conflict resolved between #413 and #352
